### ISSUE TITLE
CFD-173 : Document add widget

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#254]
Follow up of #213

### Multiple documents

A discussion can have multiple documents ([Wireframe](https://projects.invisionapp.com/d/main#/console/1420103/33869466/preview)).

### Uploaded document should be removable

A user must have the option to remove an uploaded file from the discussion attachments ([Wireframe](https://projects.invisionapp.com/d/main#/console/1420103/33869466/preview))..

### Do not add the document when cancel is clicked

* When a user drag-drop file (or browse) a popup is opened. 
* When the cancel button link is clicked: **no file should be added to the Discussion**.

### Not all uploaded documents need to go in the library
When a user uploads a document, he should have the choice to put it in or not in in the Document library ([Wireframe](https://projects.invisionapp.com/d/main#/console/1420103/41927645/preview)).

### Upload popup form should be titled "Upload Document"
When you upload a document, the popup form has as title "Quick Post". That should be "Upload Document"

### File popup should not be pre-filled with Discussion form data
When you upload a document (while editing an existing discussion), the popup form opens already pre filled with the data of the edited discussion.
The form should be empty!

## Example of the expected flow

![c4m-add-discussion-file](https://cloud.githubusercontent.com/assets/133124/5226161/14beeca6-76ec-11e4-8e56-08bab70c561f.gif)

**Comment by HelenaEksler** [comment]
@zero2one I think we can close this issue, because it's related to the angular full form, which we are not using any more.

**Comment by nader77** [comment]
@HelenaEksler Please add the widget you created for the full form to all the content types, Except for:
* Task
* task-list
* Wiki page

Those i have added in another PR.

**Comment by zero2one** [comment]
QC ok, merged
