### ISSUE TITLE
CFD-277 : Error when trying to delete a group node.

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#310]
![group_delete](https://cloud.githubusercontent.com/assets/8306902/5525672/521cf4d0-89f2-11e4-97a8-585c4a823aa6.gif)

**Comment by zero2one** [comment]
This is still an issue:

![c4m-group-delete-error](https://cloud.githubusercontent.com/assets/133124/5973228/2ec8cb20-a866-11e4-9b62-b5fa87c63d32.png)

**Comment by zero2one** [comment]
The error is not triggered by the node delete itself: when you delete a node from within the node context (PURL path) the user is redirected to the home page. Because of an active PURL path when the delete form is created, the redirect path is also PURL prefixed.

 I will:
* Fix the redirect path after an group node delete (form alter).

**Comment by zero2one** [comment]
@amitaibu It's a problem with PURL:

When a group node is deleted, og_purl deletes the record for that node in the purl table => OK.
BUT… PURL caches all the know paths in the purl module (an entry for each language) and that cache is not cleared => PURL loads the path prefix out of the cache, og_context tries to load & validate the group access > ERROR.

The proper code when deleting a node in og_purl should be:
```
/**
 * Implements hook_node_delete().
 */
function og_purl_node_delete($node) {
  $modifier = array(
    'id' => $node->nid,
    'provider' => 'og_purl|node',
  );
  purl_delete($modifier);
}
```

Tested it:
* Record in the PURL table is removed > OK.
* The path of the node that has been deleted is not removed from the cache (purl_modifiers_en) entry.

Debugging purl now…

**Comment by zero2one** [comment]
@amitaibu Purl has also an error when an cache reset is triggered.

Created issues & patches for both projects on drupal.org:

* purl : https://www.drupal.org/node/2419261#comment-9580939
* og_purl : https://www.drupal.org/node/2419277#comment-9580975

**Comment by amitaibu** [comment]
Ok, for now you can add those patches in the make file, in order to close the issue

**Comment by zero2one** [comment]
Pull request created, build is running.

**Comment by zero2one** [comment]
QC OK > Merged
