### ISSUE TITLE
CFD-212 Full form : Events - Add file field widgets

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#353]
[Invision](https://projects.invisionapp.com/d/main#/console/1420103/33869468/preview)

Please add the Document widget:
![selection_051](https://cloud.githubusercontent.com/assets/7369740/5610862/b3af268a-94c6-11e4-9fd7-72c2f78684db.png)

**Comment by nader77** [comment]
Add document widget to all the necessary content types.

**Comment by zero2one** [comment]
Form elements are not in the proper order.
  
Desired field order:
  - Title
  - Make this a subpage of (Book structure)
  - Body
  - Documents
  - Topics
  - Categories
  - Date
  - Language
  - Regions & Countries
  - Tags

**Comment by zero2one** [comment]
The file fields are replaced by the file widgets but the file field labels are missing.

![c4m-event-form-files](https://cloud.githubusercontent.com/assets/133124/5642822/5e49d18c-9650-11e4-935e-6f09766a7118.png)

**Comment by zero2one** [comment]
QC OK, merged
