### ISSUE TITLE
Drop file.

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#354]
* Can't see the "Drop file here to upload", because its in white. 
![selection_052](https://cloud.githubusercontent.com/assets/7369740/5610931/ed4ee78a-94c7-11e4-8b54-3b9cb36d6232.png)

* When dropping a file it's not working as expected, Redirects to an empty page:
![selection_053](https://cloud.githubusercontent.com/assets/7369740/5610937/138dfa44-94c8-11e4-904a-2eaf3b7907fa.png)

**Comment by zero2one** [comment]
QC OK, merged.
