### ISSUE TITLE
CFD-158: Full form : Wiki Page: Re-order form elements.

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#379]
Form elements are not in the proper order.

Desired field order:
* Title
* Make this a subpage of (Book structure)
* Body
* Documents
* Topics
* Categories
* Date
* Language
* Regions & Countries
* Tags

**Comment by HelenaEksler** [comment]
Which is "Make this a subpage of (Book structure)" field?

![create wiki page capacity4more](https://cloud.githubusercontent.com/assets/8306902/5648223/ae247726-9695-11e4-972c-f507af0ce0db.png)

**Comment by zero2one** [comment]
It is the book outline element.

We should hide the Weight & the button.
We should rename the "Parent item" label to "Make this a subpage of"

**Comment by HelenaEksler** [comment]
@zero2one I'm not totally clear on what needs to be changed, so just to prevent confusion - can you please attach  screenshot of what exactly is needed.

**Comment by zero2one** [comment]
@HelenaEksler 
I just noticed that the field is only in the wrong place for site admins.
It is correct for normal users. No further changes needed for this field.

**Comment by HelenaEksler** [comment]
@zero2one 
So I'll just move the "Book outline" block to the right place, but won't change it. Write?

**Comment by zero2one** [comment]
@HelenaEksler 
Yes!

**Comment by zero2one** [comment]
QC OK, merged

See #378
