### ISSUE TITLE
CFD-211: Full form : Document : Re-order form elements.

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#380]
Form elements are not in the proper order.

Desired field order:
  - Document (file upload)
  - Title
  - Description
  - Type of document
  - Topics
  - Group Categories
  - Date
  - Language
  - Regions & Countries
  - Tags

**Comment by HelenaEksler** [comment]
See https://github.com/capacity4dev/capacity4more/pull/373

![create document capacity4more](https://cloud.githubusercontent.com/assets/8306902/5648148/1fc4fea6-9695-11e4-84ee-9674507e4ca0.png)
