### ISSUE TITLE
CFD-212: Full form : Event : Re-order form elements

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#381]
Form elements are not in the proper order.

Desired field order:
- Title
- Type of event
- Description
- Organised by
- Event website
- Facebook page
- Twitter page
- When
    - Start date/time
    - End date/time
- Where
    - Name (venue name)
    - Street & number
    - Postal code
    - City
    - Country
- Documents
    - Agenda & informaton
    - Presentations
    - Additional
- Topics
- Categories
- Language
- Regions & Countries
- Tags

**Comment by HelenaEksler** [comment]
See https://github.com/capacity4dev/capacity4more/pull/373

![create event capacity4more](https://cloud.githubusercontent.com/assets/8306902/5648142/0eabc974-9695-11e4-9157-99fba2bdbd0f.png)
