### ISSUE TITLE
CFD-250 : c4m-app should only be loaded on pages where it is needed

### ISSUE THREAD

**Issue by amitaibu** [capacity4dev/capacity4more#385]

**Comment by HelenaEksler** [comment]
@amitaibu  Could you add some description of what should be done here?

**Comment by zero2one** [comment]
Right now, the c4m-app (angular) is loaded on every page + the body attributes are altered.
Thats not needed.
Can we:
Create a c4m_app_init_js() function that:
Sets the proper body tag attributes
Runs the needed drupal_add_js & drupal_add_css functions to load the necessary dependencies.
Call that function everywhere where the functionality (quick post, form field widgets) requires it.

**Comment by zero2one** [comment]
QC OK, Merged.
