### ISSUE TITLE
CFD-249: Field widgets : Group category 1ste level should not be selectable

### ISSUE THREAD

**Issue by amitaibu** [capacity4dev/capacity4more#386]
It's just used for grouping the terms under it.

![gotomeeting_viewer_-_talking__peter_decuyper](https://cloud.githubusercontent.com/assets/125707/5660334/b5c8f2bc-9727-11e4-93e1-4ecbd414b37e.jpg)

**Comment by zero2one** [comment]
The Group category taxonomy is special:

* The 1ste level term is only used to group the second level. 
* The first level should not be selectable. 
* Used it only to display titles as separators in the popup widget.
* The titles should not be included in the popup search box.
* Use the titles in the popup to click-expand/collapse the terms within that group.
* Show the 1ste level only in the group categories (form) if there are terms of that group selected.
* 1st level can not be removed from the form, it automatically disappears if all its child terms are removed.

**Comment by HelenaEksler** [comment]
@zero2one Some items are not clear for me. Could you add some details?
* The titles should not be included in the popup search box.
* Show the 1ste level only in the group categories (form) if there are terms of that group selected.
* 1st level can not be removed from the form, it automatically disappears if all its child terms are removed.

**Comment by zero2one** [comment]
@HelenaEksler 

Workflow:

1. User clicks on the Categories button.
2. Popup opens.
3. The popup shows the 1ste level terms as expandable links.
4. User clicks on one of the links.
5. The list expands, all terms (2nd level) beneath the clicked link.
6. User can select the 2nd level terms

**NOTE:** selecting the 2nd level terms **does not select the 1 level term**. The first level is never selectable.

See wireframes:

![c4m-group-categories](https://cloud.githubusercontent.com/assets/133124/5680276/433421ec-980b-11e4-8fec-61e5ad7961a5.gif)

**Comment by zero2one** [comment]
QC OK, Merged
