### ISSUE TITLE
CFD-255 : Quick Post : not working in a newly created group

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#402]
Quick post does not work within a newly created group:
- Create a new group (public/private/restricted).
- Go to the group dashboard.
- Click the discussion option in the quick post form.
- Fill in the title.
- Fill in the description.
- Hit save

Expected behavior:
- Form data is saved > NOK
- Form collapses > NOK
- Activity stream is updated with the new item > NOK

It does work in the (auto created) Nobel Prize group.

**Comment by zero2one** [comment]
QC OK, Merged.
