### ISSUE TITLE
CFD-259 : Quick Post : add the location name to the event form

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#407]
The location name should be added to the quick post form for events.
Add it in the same block as the address (street, postal, city, country).
The field is already available in the content type.

**Comment by HelenaEksler** [comment]
![image](https://cloud.githubusercontent.com/assets/8306902/5754593/856b7e4c-9ca3-11e4-8d66-e8f392a372de.png)

**Comment by zero2one** [comment]
QC OK, merged.
