### ISSUE TITLE
CFD-263 : Group Dashboard loads to slow (+2s)

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#413]
Follow up #400 
The group dashboard loads way to slow.
I believe that the problem is within the QuickPost form implementation.
See [BlackFire trace](https://blackfire.io/profiles/f07250db-5bbf-4b3e-b76c-a8c02b499d44/graph)
Can you optimise the QuickPost so it does load as less as data as possible upfront.
Use ajax callbacks per widget to speed up the page.

**Comment by zero2one** [comment]
on hold for now.
