### ISSUE TITLE
CFD-256 : Group Permissions : overview pages should not be accessible for restricted & private groups

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#420]
The group content overview pages:
no wiki pages page
discussions
library
events
task lists
members
Should not be accessible for non group members.
Restricted groups:
The logged in user should see them IF his email address is allowed for that group.

**Comment by HelenaEksler** [comment]
@zero2one can we convert those Views pages to be under Panels? Like this we wouldn't have to develop anything, as Panels will already return an access denied if no OG context is found.

**Comment by zero2one** [comment]
Implement the fix for the group dashboard (that is a panel).

We will then check & replace the views pages (overview pages) and replace them by panels.

**Comment by zero2one** [comment]
QC OK > Merged.
