### ISSUE TITLE
CFD-247 : Group content forms : Automatically set group audience based on group context

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#422]
When we create content within a group context (eg nobelprize/node/add/discussion) the full form asks for the group we want the post the content in.
We already know the current OG context trough the usage of PURL.
Alter the forms when the node form is used within a group context:
-Set the group audience based on the OG context. 
-Hide the OG audience field(s) for the user.

**Comment by HelenaEksler** [comment]
@zero2one  Should fields be prepopulated when nodes are editing? Or we can change group reference?

**Comment by amitaibu** [comment]
@HelenaEksler once a node was created, non admin, shouldn't be able to edit the field (i.e. keep it hidden)

**Comment by zero2one** [comment]
QC ok, merged.
