### ISSUE TITLE
CFD-271 : Travis Builds stop due to timeout

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#426]
Travis has a hard run limit of 50min.

The current builds take around 49min and sometimes more.
Hitting the timeout marks the tests as failed.

We need to see if we can speed-up testing:
* Make the installation faster (install js libraries trough make file instead of bower/grunt?).
* Run the behat tests faster (why are they that slow?).
* ...

See #426

**Comment by amitaibu** [comment]
Example of a 50min failure
https://travis-ci.org/capacity4dev/capacity4more/builds/47625069#L2086

**Comment by zero2one** [comment]
I created a branch and added "date" calls in it so we can see how long that each part of the job takes.

See: #430

**Comment by zero2one** [comment]
I have a question about PhantomJs:

During the install phase we [install PhantomJs](https://github.com/capacity4dev/capacity4more/blob/feature/CFD-271_CI_split_test_build/.travis.yml#L20-L31).

But the Travis-CI documentation states that [PhantomJs is preinstalled](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS).
Do we still need to install PhantomJS separately?

**Comment by amitaibu** [comment]
> Do we still need to install PhantomJS separately?

No, it can be removed.

**Comment by zero2one** [comment]
### I finished the fixes for the Travis-CI build.

I splitted the build in 2 jobs:
* Job 1 Installs the whole platform and performs following tests:
  * Behat tests with all tests tagged with @api
  * Simpletest
  * Coder review
* Job 2 Installs the whole platform and performs following tests:
  * Behat tests with all tests tagged with @javascript

This is the current running time of both jobs:
* **Job 1** : ~28min
* **Job 2** : ~40min

### I also cleaned the travis.yml build scenario:
* All steps needed to install a service (or to run a set of tests) are now each in a separate script (located in the `/build/travis/bin` folder).
* All configuration needed to setup the Travis environment is copied from `/build/travis/config`.
* Not all steps are run in both jobs, they have a build in step to see if they are really needed (eg. phantomJs is not run while running the behat tests with the @api tag).

### How to define what tests to run in which build

I use the [matrix](http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix) functionality of Travis-CI to split the test build in 2 jobs.

This is done by settings different variables per environment:
```
env:
  # Create a build job per BEHAT feature TAG
  - BEHAT_TAG="api"
    CODE_REVIEW=1
    SIMPLETEST=1
  - BEHAT_TAG="javascript"
    CODE_REVIEW=0
    SIMPLETEST=0
```

This are the variables in use:
* **BEHAT_TAG** (string) : What tags to include in the behat test. The value should not include the @ sign.
* **CODE_REVIEW** (int) : Should the coder review (code style) be run on the capacity4more code.
* **SIMPLETEST** (int) : Should the simpletest script be run (only this in the group “capacity4more”).

**Comment by zero2one** [comment]
Merged.
