### ISSUE TITLE
CFD-269 : Group Activity Stream : Change order

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#428]
The activity stream is not ordered by timestamp of the message, but by ID (order the message was added to the database).
While this might be no issue when using on a live site, this is an issue after running the migration.
Messages are now added in groups per content type (order of migration: first events, then documents, blog, wiki..., then all comments on events, comments on documents, ...), resulting in an activity stream that is not correct.

**Comment by zero2one** [comment]
QC OK, Merged.
