### ISSUE TITLE
CFD-281 : Vertical tabs are broken

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#446]
Helena added following lines to kapablo_overay.js:

```
if (Drupal.behaviors != 'undefined') {
  Drupal.behaviors.verticalTabs = {
    attach: function () {}};

  Drupal.behaviors.collapse = {
    attach: function () {}};
}
```

This breaks the vertical tabs (and leads to broken interfaces).
Can the vertical tabs behaviour be restored please!

**Comment by HelenaEksler** [comment]
![selection_197](https://cloud.githubusercontent.com/assets/8306902/5998580/8c7a0a1e-aad1-11e4-8a27-0a25bee653b1.png)

**Comment by zero2one** [comment]
QC OK > Merged
