### ISSUE TITLE
CFD-284 Homepage : Create layout (panel)

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#455]
Create a 2-column panel layout:

![image](https://cloud.githubusercontent.com/assets/8306902/6096057/6a2b1b10-af86-11e4-9ae4-342b57e337f8.png)

https://projects.invisionapp.com/d/main#/console/1420103/61262181/preview

Add 3 Page variants for the home page
[Anonymous user](https://wiki.amplexor.com/confluence/display/C4DNG/Home+page+-+Anonymous+user)
[Logged in user without groups](https://wiki.amplexor.com/confluence/display/C4DNG/Home+page+-+Authenticated+user+-+No+member)
[Logged in user that is member of groups](https://wiki.amplexor.com/confluence/display/C4DNG/Home+page+-+Authenticated+user+-+Member)

**Comment by zero2one** [comment]
QC OK > Merged.

**Comment by HelenaEksler** [comment]
@zero2one Can I close this issue?
