### ISSUE TITLE
CFD-310 Homepage : Create new content type "Featured"

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#459]
Module

- machine name : *c4m_content_featured*
- Name : *Featured content type*
- Group : *capacity4more - Content*
- Folder : *c4m/content/c4m_content_featured*

Content type "featured"

- Content type machine name: *featured*
- Content type name : *Featured*

Fields:

 Name | Type | Description 
--------- | ------- | ----------------
 title | text | The Drupal title field 
 body | c4m_body | The body field. Use plain text 
 image | c4m_media | Media field used to upload/select the image for the featured item 
| link | c4m_link | Link to the content (intern or extern) for the featured item |

**Comment by zero2one** [comment]
QC OK > Merged.
