### ISSUE TITLE
CFD-309 : Homepage : Add extra Voices & views fields needed for the carousel

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#465]
Add extra fields to Article content type:
* intro text (used in caroussel and overview page)
* wide banner image (for caroussel)
* checkbox to promote to carroussel (= default Drupal "Promote to front").
* checkbox to switch on/off stickyness (= default Drupal "Sticky").

**Comment by zero2one** [comment]
QC OK > Merged.
