### ISSUE TITLE
CFD-286 Homepage : Featured block

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#472]
Create the featured pane as described in the FA, wireframe & designs:
![image](https://cloud.githubusercontent.com/assets/8306902/6125378/1c7883e6-b11e-11e4-9337-9d35ecbf544a.png)![image](https://cloud.githubusercontent.com/assets/8306902/6125382/244ed8a4-b11e-11e4-8531-c0c9056e56da.png)

Add the pane to the homepage for:
- Anonymous users
- Logged in user (with or without groups)

**Comment by HelenaEksler** [comment]
@zero2one Where can I get some demo data to migrate for Featured nodes?

**Comment by zero2one** [comment]
@HelenaEksler There is no demo data yet for Featured.

You could add it using the c4m_demo_content module.

The featured items should link to the content within groups.
Could you add 5 featured items and link them to existing content within the Nobelprize group?
* 3 Discussions
* 2 Documents
* 1 Event

You will have to search for an image of each for them.
Nobelprize is a easy subject to find [images](https://www.google.be/search?q=nobelprize&es_sm=119&source=lnms&tbm=isch&sa=X&ei=uh7aVO6zPMWtPNyNgXA&ved=0CAgQ_AUoAQ&biw=1442&bih=763&dpr=1) & content.

**Comment by zero2one** [comment]
QC OK > merged the functionality.

See follow up task for theming: #491
