### ISSUE TITLE
CFD-311 : Homepage: Add video to header about "what is C4D"

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#475]
Only for anonymous users:
Add a video link to the header of the website.
The link opens a popup window in an overlay that plays a youtube video

**Comment by zero2one** [comment]
@nader77 The video needs to be in the header of the site not in the panel.

The video (for not-logged-in users) is not within the panel but within the header of the site.
You will need to create a block for it and put it there using context.

**Comment by zero2one** [comment]
QC OK > Merged.
