### ISSUE TITLE
CFD-296 Home page : Suggested Groups (Logged-in users)

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#479]
Suggested groups block contains:

- max. 3 groups are randomly selected and listed matching to following conditions:
  - accessable to user:
    - public group or 
    - restricted group and user mail adres part of matching domain 
  - AND which are tagged with at least one topic of interest of the authenticated user.
  - AND which have status published (no draft or archived)  
- in case no group is found, this block is hidden. Explicit trigger required for user to explore groups?
- for each displayed group, following info is shown:
  - group-type icon
  - group name (clickable, link to group dashboard)
  - group owner (clickable, link to public person profile)
  - number of group members
- 'see more' link leads to group overview page.

**Comment by zero2one** [comment]
QC OK > Merged.

Follow up: #507
