### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#493]
We still don't have images for banners to put on top of the homepage:

Anonymous user:
![selection_207](https://cloud.githubusercontent.com/assets/8306902/6209363/e7b48b6e-b5cd-11e4-8a52-fc2a25fea338.png)

Authenticated user:
![selection_208](https://cloud.githubusercontent.com/assets/8306902/6209365/e92e2194-b5cd-11e4-976d-ca231b4ca026.png)

And where can we get the video for the Not yet member block:

![selection_209](https://cloud.githubusercontent.com/assets/8306902/6209380/10f177e4-b5ce-11e4-9f4b-be69f6cc67de.png)

**Comment by zero2one** [comment]
@HelenaEksler 

## Images (PSD)
See dropbox.

> **NOTE**: The video (for not-logged-in users) is not within the panel but within the header of the site.
> You will need to create a block for it and put it there using context.
> See #475

![c4m-homepage-anonymous](https://cloud.githubusercontent.com/assets/133124/6243508/216b7a9a-b743-11e4-909a-fc6d925d42b8.jpg)  ![c4m-homepage-user-nogroups](https://cloud.githubusercontent.com/assets/133124/6243509/2584d3ec-b743-11e4-813d-8f19068d9315.jpg)

## Video
The video does not exist yet.
Use this video for now: https://www.youtube.com/watch?v=ISNcUnbQkVQ

**Comment by nader77** [comment]
@zero2one A question about the suggested group video, The picture to play the video is just a static picture that will not change or it will change ?
Should we give the admin ability to change the video or not ?
It's not clear in the Wireframe, if the image is editable by admin as well or not, I will have to use the video plugin i created earlier for this, So please keep it when you Fix the "What is C4D" video.
