### ISSUE TITLE
CFD-294 : Homepage : My Groups (Logged-in users) - theming

### ISSUE THREAD

**Issue by zero2one** [capacity4dev/capacity4more#500]
Follow up of:
* #478
* #492

Theming of the my-groups block.

The text on the button beneath the list should be:

* When collapsed: Show all
* When expanded: Show less

See https://projects.invisionapp.com/d/main#/console/2556061/63532996/preview

![c4m-homepage-my-groups](https://cloud.githubusercontent.com/assets/133124/6226733/a2856718-b698-11e4-9e0b-d6b2b6cec670.png)

**Comment by nader77** [comment]
@zero2one Do you know the name of the font used for titles, I can't find font configuration in the theme.

**Comment by zero2one** [comment]
@nader77 I can't find it in the color & icon overview page:
https://projects.invisionapp.com/d/main#/console/2556061/57062216/preview

Inspecting existing titles (group dashboard) show me that its:
"font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"

It's the default body font.

![c4m-font](https://cloud.githubusercontent.com/assets/133124/6245471/511f96f6-b75f-11e4-9695-e3ef62c5a933.png)

**Comment by nader77** [comment]
Ok i will give it the same class as the other, Won't add new scss.

**Comment by zero2one** [comment]
@nader77 Don't show the "Show all" button if there are no more groups to show (3 or less groups).

![c4m-my-groups-show-all](https://cloud.githubusercontent.com/assets/133124/6282985/ea71351a-b8dd-11e4-8f7a-a0292251073f.png)

**Comment by zero2one** [comment]
QC OK > Merged.
