### ISSUE TITLE
CFD-320 : Homepage : Activity stream should contain only trimmed text

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#526]
The activity list body should contain only a trimmed version of the content.
We need to create a new display mode : "activity trimmed".
Add the same fields as the normal activity view mode
BUT
Change the way the body is rendered:
Strip all tags.
Trim down to 150 characters (trim based on words).
Add "…" behind the last word.

**Comment by zero2one** [comment]
QC OK > Merged.
