### ISSUE TITLE
CFD-372 Group approval workflow: Extend groups with extra field "status"

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#536]
Add extra field to the group nodes:
- Human name : Status.
- Machine name : <b>c4m_og_status</b>
- Type : List

Add the field to the c4m_field_og module.
This field has following options:
- Requested
- Draft
- Published
- Archived
- Rejected
- Deleted

The default value is <b>Requested.</b>

**Comment by HelenaEksler** [comment]
@zero2one 
in this [table]( https://wiki.amplexor.com/confluence/display/C4DNG/Group+approval+workflow#Groupapprovalworkflow-Grouprights) and in diagram above it "Site admin" means user that can "administer site" or "administer nodes"? I mean if this is the only admin (uid = 1) or each user with administrator role like mariecurie?

**Comment by amitaibu** [comment]
Maybe let's go with the "administer site configuration" user permission

‫ב-25 במרץ 2015, בשעה 14:34, ‏HelenaEksler <notifications@github.com> כתב/ה:‬

**Comment by zero2one** [comment]
@amitaibu /cc @HelenaEksler 
I agree, lets go with the **administer site configuration** user permission.
