### ISSUE TITLE
CFD-370: In the picture : Add blocks above overview pages.

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#540]
### Create a new view:
* Machine name : c4m_overview_inthe_picture
* Human name : Overview : In the Picture

### View settings:
* Show only *published* content.
* Show only *In the Picture* nodes.
* *Order by date created* desc.
* Use the *teaser display* mode.
* No pager, show all items.

### Create a block view per In the Picture page:
* Voices & Views
* Groups
* Projects
* Events
* People

Do not show any content if no results.

## Create context
All the overview pages are view pages and are using context to place the (facet) blocks.

Add a context per overview page that adds the proper views block in the *highlighted* page region.

### Context machine names:
* *c4m_overview_inthe_picture_voicesandviews* : adds the view block (show only inthe_picture nodes that are set to be shown on the the voices & views overview page) to the path */voicesandviews*.
* *c4m_overview_inthe_picture_groups* : adds the view block (show only inthe_picture nodes that are set to be shown on the the groups overview page) to the path */groups*.
* *c4m_overview_inthe_picture_projects* : adds the view block (show only inthe_picture nodes that are set to be shown on the the projects overview page) */projects*.
* *c4m_overview_inthe_picture_events* : adds the view block (show only inthe_picture nodes that are set to be shown on the the events overview page) to the path */events*, */events/upcomming* and */events/past*.
* *c4m_overview_inthe_picture_people* : adds the view block (show only inthe_picture nodes that are set to be shown on the the people overview page) to the path */people* and */people/table*.

## Create a new module
Export the view and the contexts to a new module:

* Machine name: c4m_features_inthe_picture
* Human name : In the Pictures overviews
* Description : Adds "In the Picture" blocks above the global overview pages.

**Comment by nader77** [comment]
@zero2one What do you mean by ''filtered by the voices & views page" in the Create context section ?

**Comment by zero2one** [comment]
@nader77 I copied the text of the first bullet and forgot to change the text.

I updated the description, hope this answers your question.

**Comment by nader77** [comment]
@zero2one Yes thanks.
