### ISSUE TITLE
CFD-377: Group approval workflow : Add group management overview.

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#548]
Add a view to list all groups of the platform:

## View name

Human name : Admin : Groups
Machine name : c4m_admin_groups
Description : Administration interface to manage groups & their status.
URL : admin/c4m/groups
Type : Table view

#### Fields

The following fields should be in the table view:

* **Name** : The group name. Link to the group detail node (PURL prefixed).
* **Status** : The group status.
* **Owner** : The owner of the group (link to user detail page).
* **Created** : The group creation date.
* **Edit** : A link to the group edit form.

#### Filter

Add an Exposed filter above the view with following fields:

* **Name** : Search groups based on the group name (text field, field contains).
* **Status** : Filter the groups based on the status (select dropdown).

## Add new module

Add the overview to the *c4m_admin_groups* module within the *modules/c4m/admin/c4m_admin_groups* directory.

**Comment by nader77** [comment]
Outline:
* Add new view.
* Add new module.

**Comment by zero2one** [comment]
@nader : I forgot the exposed filters above the table view.

#### Filter

Add an **Exposed filter** above the view with following fields:

* **Name** : Search groups based on the group name (text field, field contains).
* **Status** : Filter the groups based on the status (select dropdown).
