### ISSUE TITLE
Bug: Group's required fields are not marked on validation.

### ISSUE THREAD

**Issue by solker** [capacity4dev/capacity4more#551]
If you try create a new group from non-platform admins and doesn't select `Group topics` or `Regions & Countries` you will receive the error message with a next text "field is required.". But unselected  field doesn't mark as incorrect, for example by red star or red border. Therefore a user doesn't know where is a problem.

![bag_group_add](https://cloud.githubusercontent.com/assets/10127295/6819729/9058f3f0-d2ce-11e4-88dc-aa3c070d847e.png)
![bug_form](https://cloud.githubusercontent.com/assets/10127295/6819731/9ad08d5c-d2ce-11e4-9d28-8e725e45feb9.png)

**Comment by nader77** [comment]
@solker Create issue in Jira.
