### ISSUE TITLE
Banners on overview pages should link to content detail

### ISSUE THREAD

**Issue by MPParsley** [capacity4dev/capacity4more#563]
Currently it is not possible to click on the banner on the voices & views carousel on the homepage. See #541.

**Comment by solker** [comment]
Since this is related to a WIP PR, I'll move this comment there

**Comment by MPParsley** [comment]
@solker in what PR did you implement this?

**Comment by solker** [comment]
@MPParsley https://github.com/capacity4dev/capacity4more/pull/569
