### ISSUE TITLE
CFD-411: Voices & views carousel should link to Article detail page

### ISSUE THREAD

**Issue by solker** [capacity4dev/capacity4more#567]
Currently it is not possible to click on the banner on the voices & views carousel on the homepage.

From wiki:
> clicking any location of the currently shown caroussel item leads to an existing voices & views article

See #/563

**Comment by solker** [comment]
@MPParsley One way to do it, it's disable touch slide moving function at all. Because every touch equal to click and click equal to forward by link. It's mean safe only arrows for navigation between slides.

**Comment by solker** [comment]
@MPParsley We decide to attach the link to a info box. Red box is a link now. We think its a best compromise solution that safe touch sliding and have a link inside. What you think about it? 
![infobox](https://cloud.githubusercontent.com/assets/10127295/6937708/17e5548e-d866-11e4-98b9-d00a29ed8a2f.png)

**Comment by HelenaEksler** [comment]
@zero2one  Can you answer on the upper comment?

**Comment by nader77** [comment]
Please move your question to Jira if it's still relevant.
