### ISSUE TITLE
CFD-412: Group Approval Workflow : Update migration

### ISSUE THREAD

**Issue by solker** [capacity4dev/capacity4more#568]
We need to update the migration so the groups get the proper status:

* Groups that are published > Published
* Groups that are unpublished > Draft

Make sure that no notifications are send during the migration.

https://issuetracker.amplexor.com/jira/browse/CFD-412

**Comment by zero2one** [comment]
Migration code is in : https://github.com/capacity4dev/c4d_import

**Comment by solker** [comment]
@zero2one what about a dump of data for test?

**Comment by solker** [comment]
@zero2one demo content with published status already have Published status, and draft content also have Draft status. Content with unpublished status not exists in demo content. Therefore I can change behavior of migrate module only for unpublished items that should be Draft.

**Comment by zero2one** [comment]
It's not about the demo content it's about the migration of the real data.

We will take care of it.
