### ISSUE TITLE
CFD-383: Group management HUB : Add anchors in the group edit form.

### ISSUE THREAD

**Issue by YuriGizra** [capacity4dev/capacity4more#575]
### Alter the group node form

Add to the "c4m_features_og_manage" module a form alter for the group node form.

Add anchors to the following elements by adding an ID on their elements:

ID name | Field | Description 
------------|---------|--------------
 edit-details | Group name (node title) | Link to the group name field 
 edit-permisssions | Group access | Link to the group access settings 
 edit-related-content | Subgroup of | Link to the related content settings 
 edit-image-banner | Banner image | Link to the banner image 
 edit-image-list | Thumbnail image | Link to the list image 

### Update the Group management HUB page

Update the links on the Group management page (<group-prefix>/manage).
Add the anchor to the Edit links for:

* Group Banner
* Group Details
* Group Permissions
* Related Content
* Thumbnail Image

**Comment by zero2one** [comment]
QC OK > Merged
