### ISSUE TITLE
CFD-343 cannot confirm if document should be in the library

### ISSUE THREAD

**Issue by HelenaEksler** [capacity4dev/capacity4more#622]
When I create an event and want to add a document, I am asked to say if this document should live in the library or not - but the yes and no buttons cannot be selected - leaving me with the option to cancel. As a result, I cannot upload the document. This was tested both on IE and Safari through the full creation form, using drag and drop on safari + browse and drag and drop on IE. 

The same bug occurs for discussions

**Comment by zero2one** [comment]
QC OK > Merged
