### ISSUE TITLE
Fork of github repositories.

### ISSUE THREAD

**Issue by nader77** [capacity4dev/capacity4more#886]
There's 2 dependencies of GitHub repos in the make file:

* Gizra/pluggable_node_access
* HelenaEksler/og

Should be forked by this organization and change the dependency in the make file.

**Comment by soniCaH** [comment]
- Forked OG to the organisation and updated the URL in the make file.
- Moved pluggable_node_access to the drupal.org project download as it was using the default 1.x-dev branch anyway.

**Comment by soniCaH** [comment]
See https://github.com/capacity4dev/capacity4more/pull/917
